### ISSUE TITLE
Local, Global, and Hybrid Modes Not Working in HF Example

### ISSUE THREAD

**Issue by shmily1012** [HKUDS/LightRAG#109]
I'm using the Hugging Face example from the LightRAG repository, and only the naive mode functions correctly. The local, global, and hybrid modes fail to work.

LLM Model: llam3.1 8b instruct
Embed Model: all-MiniLM-L12-V2

Any advice?

**Comment by TianyuFan0504** [comment]
Hi @shmily1012.
We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models.
Your problem may arise from the following reasons:
1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed
2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.

After our testing, models above 14B can generally perform well

**Comment by DayanaYuan** [comment]
> Hi @shmily1012. We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models. Your problem may arise from the following reasons: 1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed 2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.
> 
> After our testing, models above 14B can generally perform well

my code is follow:

**Comment by DayanaYuan** [comment]
> Hi @shmily1012. We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models. Your problem may arise from the following reasons: 1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed 2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.
> 
> After our testing, models above 14B can generally perform well

my code is follow:WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,
    llm_model_name="/LightRAG/examples/meta-llama/Llama3-8B-instruct",
    # llm_model_name="meta-llama/Llama-3.1-8B-Instruct",
    embedding_func=EmbeddingFunc(
        embedding_dim=384,
        max_token_size=5000,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained(
                "LightRAG/examples/sentence-transformers/all-MiniLM-L6-v2"
            ),
            embed_model=AutoModel.from_pretrained(
                "LightRAG/examples/sentence-transformers/all-MiniLM-L6-v2"
            ),
        ),
    ),
)


with open("./book.txt") as f:
    rag.insert(f.read())

# Perform naive search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="naive"))
)

# Perform local search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="local"))
)

# Perform global search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="global"))
)

# Perform hybrid search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="hybrid"))
)

but the answer is follow:agraphs

assistant

Based on the provided text, some of the top themes in this story are:

1. **Redemption and Change**: The story explores the theme of redemption as Ebenezer Scrooge, a miserly and bitter character, undergoes a transformation after being visited by the Ghost of Christmas Past, Present, and Yet to Come. Scrooge's experiences lead him to reevaluate his values and behavior, ultimately changing his ways and becoming a kinder and more generous person.
2. **Kindness and Generosity**: The story highlights the importance of kindness and generosity, particularly around Christmas. The character of Bob Cratchit, a poor but kind and hardworking man, is a prime example of this theme. The story also shows how small acts of kindness, such as the Cratchits' humble celebrations and Scrooge's eventual generosity, can bring joy and warmth to those around them.
3. **Social Class and Poverty**: The story touches on the theme of social class and poverty
INFO:lightrag:Creating a new event loop in a sub-thread.
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.03it/s]
WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.
Sorry, I'm not able to provide an answer to that question.
INFO:lightrag:Creating a new event loop in a sub-thread.
Loading checkpoint shards: 100%|██████████| 4/4 [00:06<00:00,  1.58s/it]
INFO:lightrag:Creating a new event loop in a sub-thread.
Sorry, I'm not able to provide an answer to that question.
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.03it/s]
WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.
/LightRAG/lightrag/operate.py:990: UserWarning: High Level context is None. Return empty High entity/relationship/source
  warnings.warn(
LightRAG/lightrag/operate.py:998: UserWarning: Low Level context is None. Return empty Low entity/relationship/source
  warnings.warn(
Loading checkpoint shards: 100%|██████████| 4/4 [00:06<00:00,  1.58s/it]
system

---Role---

You are a helpful assistant responding to questions about data in the tables provided.


---Goal---

Generate a response of the target length and format that responds to the 's question, summarizing all information in the input data tables appropriate for the response length and format, and incorporating any relevant general knowledge.
If you don't know the answer, just say so. Do not make anything up.
Do not include information where the supporting evidence for it is not provided.

---Target response length and format---

Multiple Paragraphs

---Data tables---


-----Entities-----
```csv

-----Relationships-----

-----Sources-----



Add sections and commentary to the response as appropriate for the length and format. Style the response in markdown.

assistant

I'm happy to help! However, I don't see any data tables provided. Could you please provide the tables for "Entities", "Relationships", and "Sources" so I can assist you in identifying the top themes in the story?

进程已结束,退出代码0 

Is this because of a problem with the 3B model?

**Comment by shmily1012** [comment]
> Hi @shmily1012. We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models. Your problem may arise from the following reasons: 1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed 2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.
> 
> After our testing, models above 14B can generally perform well

Hi @TianyuFan0504, thanks for your quick response. I am wondering if you can you provide the full name of your 14B model. I really would like to give it a try.
BR,
Alex

**Comment by shmily1012** [comment]
I will try Llama3.2 11b and Qwen2 14B today, let's see.

**Comment by TianyuFan0504** [comment]
> > Hi @shmily1012. We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models. Your problem may arise from the following reasons: 1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed 2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.
> > After our testing, models above 14B can generally perform well
> 
> Hi @TianyuFan0504, thanks for your quick response. I am wondering if you can you provide the full name of your 14B model. I really would like to give it a try. BR, Alex

There are some models we have tested:llama1b/3b/7b/11b, qwen 14b, minicpm4b, gemma2b, baichuan2b. 
Only qwen  work. : (

**Comment by shmily1012** [comment]
Qwen2 works on my test bench as well. However, I noticed that the Hugging Face generator currently has a fixed response length of 200 tokens, which may require adjustment depending on our needs.Sent from my iPhoneOn Oct 24, 2024, at 3:42 AM, Tianyu Fan ***@***.***> wrote:﻿


Hi @shmily1012. We have understood your question. Due to the diverse response formats of the HF model, we have not yet added optimizations to all models. Your problem may arise from the following reasons: 1.The reply format of llama8B is not stable and may generate unreadable JSON, resulting in the query process being unable to proceed 2.Llama8B is not strong enough to find enough entity/relation to handle this type of query.
After our testing, models above 14B can generally perform well

Hi @TianyuFan0504, thanks for your quick response. I am wondering if you can you provide the full name of your 14B model. I really would like to give it a try. BR, Alex

There are some models we have tested:llama1b/3b/7b/11b, qwen 14b, minicpm4b, gemma2b, baichuan2b.
Only qwen  work. : (

**Comment by shmily1012** [comment]
Qwen2 14B works with HF mode.

**Comment by amenhere** [comment]
我测试了qwen-vl-plus，glm-4-flash，gpt-4-turbo和gpt-4o-mini-2024-07-18都有可能出现这个问题，而且频率很高。
我提出的的问题如下：

prompt：
请根据以下每个标签后的描述，准确提取合同中每个实体的对应信息：
规则：
1、当前合同中没有这个标签实体时可以用"None"填写；
2、用中文输出；
3、实体信息必须是合同中的原文，不可以进行编造！！！
4、不要出现无关的提示词，如：我认为，总结，可能，等等；
5、用json的格式返回实体字典表和他对应的实体信息，例如：{"实体标签":"实体内容"}；

####标签解释
合同编号: 合同的唯一标识符，通常为一串数字或字母组合。用于区分不同合同。
合同名称: 合同的正式名称或标题，通常包括合同类型、签约方或项目名称等信息。
签订日期: 合同达成的日期，通常是甲方和乙方双方签署合同的具体日期。
合同有效期: 合同在法律上生效并持续有效的时间段，通常包括开始日期和结束日期。
合同主要内容: 合同的核心条款或涉及的主要事项，简要概述合同的基本约定。
服务内容: 乙方提供的服务或甲方要求乙方完成的任务和工作内容。
甲方名称: 合同中的一方，通常为发起方或委托方，常见于购买、合作或委托等合同。
乙方名称: 合同中的另一方，通常为接受方或服务提供方。
甲方纳税人识别号: 甲方在税务系统中的唯一识别号码，用于税务识别。
乙方纳税人识别号: 乙方在税务系统中的唯一识别号码，用于税务识别。
甲方地址: 甲方的注册地址或主要办公地点，通常为法人注册地或联系地址。
乙方地址: 乙方的注册地址或主要办公地点，通常为法人注册地或联系地址。
甲方电话: 甲方的联系方式，通常是电话号码，用于日常沟通。
乙方电话: 乙方的联系方式，通常是电话号码，用于日常沟通。
违约责任: 合同中规定的违约条款，描述当事一方未履行合同义务时应承担的责任。
争议解决方式: 当合同双方发生争议时，约定的解决方式，如仲裁、诉讼或调解等。

####实体字典
{
    合同编号:
    合同名称:
    签订日期:
    合同有效期:
    合同主要内容:
    服务内容:
    甲方名称:
    乙方名称:
    甲方纳税人识别号:
    乙方纳税人识别号:
    甲方地址:
    乙方地址:
    甲方电话:
    乙方电话:
    违约责任:
    争议解决方式:
}
