### ISSUE TITLE
【function】How to specify entity types and language types?

### ISSUE THREAD

**Issue by waHhhHao** [HKUDS/LightRAG#119]
When I'm trying to use LightRAG for knowledge graph generation, I encounter two issues: 1. The disease names extracted from the articles have an entity type of 'event', but I want them to be 'disease'. Also, I don't want it to extract personal names. Can I specify the entity types before the LLM extracts entities? 2. For English input, the output is also in English, but I hope it can be in Chinese.

**Comment by Dormiveglia-elf** [comment]
1. Current enetity type is fixed in function `async def extract_entities` in `operate.py` - `entity_types=",".join(PROMPTS["DEFAULT_ENTITY_TYPES"])`,  You can add a paprameter assuming named `customized_entity_types: List[str] = None` and change the default `entity_types` to `entity_types=",".join(customized_entity_types or PROMPTS["DEFAULT_ENTITY_TYPES"])`. Then you can customize your entity type if you want.
2. You can refer to prompt.tune in Microsoft Graphrag to specify any language, or you can just modify `prompt.py` to replace the English examples to Chinese examples.
