### ISSUE TITLE
lightrag_openai_compatible_demo. file. Questions to ask

### ISSUE THREAD

**Issue by redpintings** [HKUDS/LightRAG#121]
I saw that you modified the code yesterday, but I feel that there are some areas that are not correct, especially the file reading and querying parts of the asynchronous code. Would it be better to switch to asynchronous?

` with open("./hanye.txt", "r", encoding="utf-8") as f:
            content = f.read()
   await rag.ainsert(content)`

`naive_result = await rag.aquery(query, param=QueryParam(mode="naive"))
        print("Naive search result:", naive_result)`

**Comment by Dormiveglia-elf** [comment]
Actually, I give the pr yesterday just to aovid the potential embedding problem (you can check it out in the closed pull request history), the original code is not asynchronous so I keep the original style. I have tried to switch to asynchrounous as you described which indeed reduced the response time. But I think that maybe it is not necessary since it is just a demo, and the synchronous  query is much easier for users to understand. If you truly want to switch to asynchrounous, I can give another pr or you can give a pr yourself (if the author think it is acceptable).

**Comment by Dormiveglia-elf** [comment]
Sorry, I think I missed some points in the last response. The indexing and query procedure you mentioned here **should be synchronous** . If you set thme to asynchronous mode, the program will probably raise errors since **the indexing process must behind the rag initilization, and the query process must behind the indexing process**, which means the order is critical, **but the asynchronous mode cannot gurantee the order**. I said in the last response that "I tried to switch to asynchrounous..." is the case that I have already done the indexing and the initialization process, every time I just do the query process so asynchrounous mode is fast and reasonable at that time. I hope this can clarify your question.
