### ISSUE TITLE
LightRAG对比GraphRAG的local search有什么优势？What are the advantages of LightRAG compared to GraphRAG's local search?

### ISSUE THREAD

**Issue by unknown918** [HKUDS/LightRAG#196]
closed

**Comment by lajihaonange** [comment]
Eat :watermelon: in the front.

**Comment by dreamerwhite** [comment]
等答案

**Comment by LarFii** [comment]
Thank you for your attention.

Regarding your first question, I believe the comparison is reasonable. If the performance of the two methods is similar, their win rates should be close to 50%, which is also the approach taken by GraphRAG.

For the second question, I think it is necessary to consider the global method. Our evaluation framework aligns with GraphRAG's, focusing on global queries across the entire dataset. Furthermore, even for local methods, LightRAG still has an advantage in token consumption compared to GraphRAG's local method. The use of 60 entities is due to the parameter setting of topk=60. For local queries with the same number of entities, LightRAG does not require the addition of community reports, so it maintains a favorable token overhead.

Regarding the third point, I'm not sure about your specific approach, but the discrepancy you observed may be mainly due to the difference in the number of retrieved entities between GraphRAG local search and LightRAG local search, as LightRAG can be configured to retrieve more than 60 entities.

For the fourth question, as mentioned in points 1 and 2, our evaluation framework is consistent with GraphRAG's. The assessment for global questions has been presented in the paper. For local queries, keyword-based retrieval ultimately also utilizes embeddings, but we extract keywords from the query rather than performing semantic retrieval directly with the query.

Thank you again for your questions!
