### ISSUE TITLE
with vLLM embedding api，got 'Detected embedding dimension: 3584 An error occurred: Embedding dim mismatch, expected: 3584, but loaded: 768' 

### ISSUE THREAD

**Issue by 7801943** [HKUDS/LightRAG#198]
vLLM embedding model is BAAI-bge-multilingual-gemma2 , with cli "vllm serve  BAAI-bge-multilingual-gemma2" start

**Comment by 7801943** [comment]
> You may need to adjust the embed dim according to the embedding model being used.
> 
> Here i'm sharing ollama demo script as ref.
> 
> ```
> rag = LightRAG(
>     working_dir=WORKING_DIR,
>     llm_model_func=ollama_model_complete,
>     llm_model_name="gemma2:2b",
>     llm_model_max_async=4,
>     llm_model_max_token_size=32000,
>     llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 32768}},
>     embedding_func=EmbeddingFunc(
>         embedding_dim=768, ###  #Change this value accordingly
>         max_token_size=8192,
>         func=lambda texts: ollama_embedding(
>             texts, embed_model="nomic-embed-text", host="http://localhost:11434"
>         ),
>     ),
> )
> ```

thanks for reply，i don't have ollama，my embedding model served by local vLLM，llm serverd by remote Yi-lighting api， It  works after modify vdb_chunks.json entities relationships... embedding_dim  to 3584，i don't know why

**Comment by Jaykumaran** [comment]
Did you create the database directory first with the nomic-embed-text model and then try to infer using BAAI-bge-multilingual-gemma2?

If this is the case, since the nomic-embed-text embedding dimension is 768, the vector embeddings in the nanodb would have been created with an "embedding_dim" of 768. However, if you then rerun the process using another embedding model with a dimension of 3584 without deleting the database directory, there will be a mismatch, as all the vdb JSON files will contain:

```
{
    "embedding_dim": 768
}
```
This indicates that they were encoded based on the previous model.

Whenever you change your LLM or embedding model, make sure to delete the old directory or rename it to reflect the effective changes of the current run.


Hope this helps. Let me know if you need additional clarity on this.

**Comment by Jaykumaran** [comment]
Feel free to close this issue, if you got the fix and answer 😄

**Comment by 7801943** [comment]
> Feel free to close this issue, if you got the fix and answer 😄



> Did you create the database directory first with the nomic-embed-text model and then try to infer using BAAI-bge-multilingual-gemma2?
> 
> If this is the case, since the nomic-embed-text embedding dimension is 768, the vector embeddings in the nanodb would have been created with an "embedding_dim" of 768. However, if you then rerun the process using another embedding model with a dimension of 3584 without deleting the database directory, there will be a mismatch, as all the vdb JSON files will contain:
> 
> ```
> {
>     "embedding_dim": 768
> }
> ```
> 
> This indicates that they were encoded based on the previous model.
> 
> Whenever you change your LLM or embedding model, make sure to delete the old directory or rename it to reflect the effective changes of the current run.
> 
> Hope this helps. Let me know if you need additional clarity on this.

yes，you are correct，i think it was solved

**Comment by Jaykumaran** [comment]
Glad to hear you got a fix. You can consider closing this issue.
