### ISSUE TITLE
reproduce Evaluation

### ISSUE THREAD

**Issue by Christ-dev** [HKUDS/LightRAG#97]
I would like to know how to reproduce Evaluation?
Any suggestion will do.
Thank you!

**Comment by LarFii** [comment]
You can follow the [evaluation](https://github.com/HKUDS/LightRAG?tab=readme-ov-file#evaluation) section.

**Comment by Christ-dev** [comment]
> You can follow the [evaluation](https://github.com/HKUDS/LightRAG?tab=readme-ov-file#evaluation) section.

I totally understand what you talking about, but i can't figure out the relationship between the database and the python files,  generate_query.py and batch_eval.py.And Can the generate_query.py  only run with the openAI api interface?What about Ollama?
BTW, the batch_eval.py doesn't have 'query_file', 'result1_file', 'result2_file', and 'output_file_path', i'm really confused.
Thank you!

**Comment by LarFii** [comment]
Since we used 4o-mini for evaluation, we provided the OpenAI method, but you can certainly replace it with any of the other methods from the examples. The batch evaluation is based on OpenAI's API call structure, but if you're using another method, you can evaluate them one by one. The query_file refers to the file storing the queries, which is generated from step-2 (queries). Since we're doing one-to-one comparisons, result1 and result2 refer to the responses from the models being compared.

**Comment by Christ-dev** [comment]
I understand, thank you!
